version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GuineaPigApp123
    ports:
      - "1433:1433"

  server:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: ./Frontend/GuineaPigApp_Client
    ports:
      - "4200:4200"
    depends_on:
      - server